export default {
    /***************************** CATEGORY CONSTANTS STARTS *********************************** */
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

    GET_CATEGORY_BY_ID_REQUEST: 'GET_CATEGORY_BY_ID_REQUEST',
    GET_CATEGORY_BY_ID_SUCCESS: 'GET_CATEGORY_BY_ID_SUCCESS',
    GET_CATEGORY_BY_ID_FAILURE: 'GET_CATEGORY_BY_ID_FAILURE',

    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
    /***************************** CATEGORY CONSTANTS ENDED *********************************** */

    /***************************** COMPANY CONSTANTS STARTS *********************************** */
    GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_FAILURE: 'GET_COMPANIES_FAILURE',

    GET_COMPANY_BY_ID_REQUEST: 'GET_COMPANY_BY_ID_REQUEST',
    GET_COMPANY_BY_ID_SUCCESS: 'GET_COMPANY_BY_ID_SUCCESS',
    GET_COMPANY_BY_ID_FAILURE: 'GET_COMPANY_BY_ID_FAILURE',

    CREATE_COMPANY_REQUEST: 'CREATE_COMPANY_REQUEST',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAILURE: 'CREATE_COMPANY_FAILURE',

    UPDATE_COMPANY_REQUEST: 'UPDATE_COMPANY_REQUEST',
    UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
    UPDATE_COMPANY_FAILURE: 'UPDATE_COMPANY_FAILURE',

    DELETE_COMPANY_REQUEST: 'DELETE_COMPANY_REQUEST',
    DELETE_COMPANY_SUCCESS: 'DELETE_COMPANY_SUCCESS',
    DELETE_COMPANY_FAILURE: 'DELETE_COMPANY_FAILURE',
    /***************************** COMPANY CONSTANTS ENDED *********************************** */

    /***************************** NUMBER CONSTANTS STARTS *********************************** */
    GET_NUMBERS_REQUEST: 'GET_NUMBERS_REQUEST',
    GET_NUMBERS_SUCCESS: 'GET_NUMBERS_SUCCESS',
    GET_NUMBERS_FAILURE: 'GET_NUMBERS_FAILURE',

    GET_NUMBER_BY_ID_REQUEST: 'GET_NUMBER_BY_ID_REQUEST',
    GET_NUMBER_BY_ID_SUCCESS: 'GET_NUMBER_BY_ID_SUCCESS',
    GET_NUMBER_BY_ID_FAILURE: 'GET_NUMBER_BY_ID_FAILURE',

    CREATE_NUMBER_REQUEST: 'CREATE_NUMBER_REQUEST',
    CREATE_NUMBER_SUCCESS: 'CREATE_NUMBER_SUCCESS',
    CREATE_NUMBER_FAILURE: 'CREATE_NUMBER_FAILURE',

    UPDATE_NUMBER_REQUEST: 'UPDATE_NUMBER_REQUEST',
    UPDATE_NUMBER_SUCCESS: 'UPDATE_NUMBER_SUCCESS',
    UPDATE_NUMBER_FAILURE: 'UPDATE_NUMBER_FAILURE',

    DELETE_NUMBER_REQUEST: 'DELETE_NUMBER_REQUEST',
    DELETE_NUMBER_SUCCESS: 'DELETE_NUMBER_SUCCESS',
    DELETE_NUMBER_FAILURE: 'DELETE_NUMBER_FAILURE',
    /***************************** NUMBER CONSTANTS ENDED *********************************** */
}